### ISSUE TITLE
Monitoring For New Pairs/Rug

### ISSUE THREAD

**Issue by opiumhen** [danvaneijck/sol-sniper#1]
Discord UI Shows:
Monitoring new pairs: :x:
Monitoring for rugs: :x:

Terminal Shows It Checking for New Pairs.
Setting monitoring new pairs to true in discord via slash command doesn't seem to change the discord UI to yes

**Comment by opiumhen** [comment]
Not sure if auto-snipe function is not working despite UI showing it is live but its not taking trades.
Config as follows:
        const config = {
            live: true, // turn live trading on and off
            snipeAmount: 0.01, // %
            percentAddedRequirement: 0.9,
            maxTrades: 2,
            profitGoal: 200, // %
            moonBag: 1000, // %
            stopLoss: 50, // %
            tradeTimeLimit: 5, // minutes
            lowerLiquidityBound: 1000, // USD
            upperLiquidityBound: 60000, // USD
            slippage: 10, // %
        };

**Comment by opiumhen** [comment]
Note sure if we need to add a monitor for new rugs to main.ts ?

**Comment by danvaneijck** [comment]
Hi ill take a look this weekend

**Comment by danvaneijck** [comment]
there was some left over code that I ported over from another bot. I have fixed the toggle for monitoring new pairs and the status cmd returns the correct status.

**Comment by danvaneijck** [comment]
merged to main
